import { writeFileSync } from "node:fs";
import { createTheme, HUE_BLUEJAY } from "../app/theme";

type Theme = ReturnType<typeof createTheme>;
type ColorScale = Record<string | number, string>;

function suffixFor(key: string) {
  return key === "DEFAULT" ? "" : `-${key}`;
}

function emitRuntimeScale(name: string, scale: ColorScale) {
  return Object.entries(scale)
    .map(
      ([key, value]) =>
        `  --theme-color-${name}${suffixFor(key)}: ${value};`,
    )
    .join("\n");
}

function emitThemeScale(name: string, scale: ColorScale) {
  return Object.keys(scale)
    .map((key) => {
      const suffix = suffixFor(key);

      return `  --color-${name}${suffix}: var(--theme-color-${name}${suffix});`;
    })
    .join("\n");
}

function emitRuntimeTheme(selector: string, theme: Theme) {
  const { colors, layout } = theme;

  return `${selector} {
${emitRuntimeScale("primary", colors.primary)}
${emitRuntimeScale("secondary", colors.secondary)}
${emitRuntimeScale("accent", colors.accent)}
${emitRuntimeScale("foreground", colors.foreground)}
  --theme-color-background: ${colors.background};
  --theme-color-focus: ${colors.focus};
  --theme-color-editorbackground: ${colors.editorbackground};
  --theme-radius-sm: ${layout.radius.small};
  --theme-radius-md: ${layout.radius.medium};
  --theme-radius-lg: ${layout.radius.large};
}`;
}

function emitTailwindTheme(theme: Theme) {
  const { colors } = theme;

  return `@theme inline {
${emitThemeScale("primary", colors.primary)}
${emitThemeScale("secondary", colors.secondary)}
${emitThemeScale("accent", colors.accent)}
${emitThemeScale("foreground", colors.foreground)}
  --color-background: var(--theme-color-background);
  --color-focus: var(--theme-color-focus);
  --color-editorbackground: var(--theme-color-editorbackground);
  --radius-sm: var(--theme-radius-sm);
  --radius-md: var(--theme-radius-md);
  --radius-lg: var(--theme-radius-lg);
}`;
}

const light = createTheme(HUE_BLUEJAY, HUE_BLUEJAY + 0.1, false);
const dark = createTheme(HUE_BLUEJAY, HUE_BLUEJAY + 0.1, true);

const css = `/* Generated by scripts/generate-theme-css.ts. */
${emitRuntimeTheme(":root", light)}

${emitRuntimeTheme(".dark", dark)}

${emitTailwindTheme(light)}
`;

writeFileSync("app/theme.generated.css", css);
console.log("Wrote app/theme.generated.css");